apiVersion: apps/v1
kind: Deployment
metadata:
  name: usedcar-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usedcar-backend
  template:
    metadata:
      labels:
        app: usedcar-backend
    spec:
      containers:
        - name: usedcar-backend
          image: 440744253098.dkr.ecr.eu-north-1.amazonaws.com/usedcar-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: database
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:YOUR_ACCOUNT_ID:certificate/YOUR_CERTIFICATE_ID
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: usedcar-backend
  ports:
    - protocol: TCP
      port: 443 # Expose HTTPS externally
      targetPort: 8000 # Backend app listens on port 8000
      name: https
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: LoadBalancer
