apiVersion: apps/v1
kind: Deployment
metadata:
  name: usedcar-backend
spec:
  replicas: 2 # Number of backend instances
  selector:
    matchLabels:
      app: usedcar-backend
  template:
    metadata:
      labels:
        app: usedcar-backend
    spec:
      containers:
        - name: usedcar-backend
          image: 440744253098.dkr.ecr.eu-north-1.amazonaws.com/usedcar-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: usedcar-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
