apiVersion: apps/v1
kind: Deployment
metadata:
  name: usedcar-backend
spec:
  replicas: 2 # Number of backend instances
  selector:
    matchLabels:
      app: usedcar-backend
  template:
    metadata:
      labels:
        app: usedcar-backend
    spec:
      containers:
        - name: usedcar-backend
          image: 440744253098.dkr.ecr.eu-north-1.amazonaws.com/usedcar-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: database
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30 # Delay first check for 30 seconds
            timeoutSeconds: 3
            periodSeconds: 30 
            failureThreshold: 3 # Allow 3 failures before restart

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20 # Delay readiness check for 20 seconds
            timeoutSeconds: 3
            periodSeconds: 30 
            failureThreshold: 3 # Allow 3 failures before marking as "Not Ready"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: usedcar-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
