name: Deploy Backend to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest # ✅ Switch to Linux-based runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Allow Execution for Bash Script
        run: chmod +x deployment/ci_cd/deploy-backend.sh

      - name: Run Deployment Script
        run: bash deployment/ci_cd/deploy-backend.sh
